[2023-07-17 14:11:41.572][D][client_logManager.py(Init):12] LogManager Init function called !!!
[2023-07-17 14:11:44.094][I][client_model.py(connect):38] Connection refused, retrying...
[2023-07-17 14:11:51.123][I][client_model.py(connect):38] Connection refused, retrying...
[2023-07-17 14:11:58.167][I][client_model.py(connect):38] Connection refused, retrying...
[2023-07-17 14:12:05.179][I][client_model.py(connect):38] Connection refused, retrying...
[2023-07-17 14:12:12.209][I][client_model.py(connect):38] Connection refused, retrying...
[2023-07-17 14:12:19.226][I][client_model.py(connect):38] Connection refused, retrying...
[2023-07-17 14:12:26.244][I][client_model.py(connect):38] Connection refused, retrying...
[2023-07-17 14:12:33.317][I][client_model.py(connect):38] Connection refused, retrying...
[2023-07-17 14:12:40.349][I][client_model.py(connect):38] Connection refused, retrying...
[2023-07-17 14:12:47.378][I][client_model.py(connect):38] Connection refused, retrying...
[2023-07-17 14:12:54.417][I][client_model.py(connect):38] Connection refused, retrying...
[2023-07-17 14:13:01.448][I][client_model.py(connect):38] Connection refused, retrying...
[2023-07-17 14:13:08.500][I][client_model.py(connect):38] Connection refused, retrying...
[2023-07-17 14:13:15.534][I][client_model.py(connect):38] Connection refused, retrying...
[2023-07-17 14:13:22.579][I][client_model.py(connect):38] Connection refused, retrying...
[2023-07-17 14:13:29.614][I][client_model.py(connect):38] Connection refused, retrying...
[2023-07-17 14:13:36.632][I][client_model.py(connect):38] Connection refused, retrying...
[2023-07-17 14:13:43.661][I][client_model.py(connect):38] Connection refused, retrying...
[2023-07-17 14:13:50.699][I][client_model.py(connect):38] Connection refused, retrying...
[2023-07-17 14:13:57.709][I][client_model.py(connect):38] Connection refused, retrying...
[2023-07-17 14:14:04.736][I][client_model.py(connect):38] Connection refused, retrying...
[2023-07-17 14:14:11.762][I][client_model.py(connect):38] Connection refused, retrying...
[2023-07-17 14:14:18.809][I][client_model.py(connect):38] Connection refused, retrying...
[2023-07-17 14:14:25.859][I][client_model.py(connect):38] Connection refused, retrying...
[2023-07-17 14:14:32.873][I][client_model.py(connect):38] Connection refused, retrying...
[2023-07-17 14:14:39.924][I][client_model.py(connect):38] Connection refused, retrying...
[2023-07-17 14:14:46.947][I][client_model.py(connect):38] Connection refused, retrying...
[2023-07-17 14:14:53.978][I][client_model.py(connect):38] Connection refused, retrying...
[2023-07-17 14:15:01.016][I][client_model.py(connect):38] Connection refused, retrying...
[2023-07-17 14:15:08.039][I][client_model.py(connect):38] Connection refused, retrying...
[2023-07-17 14:15:15.050][I][client_model.py(connect):38] Connection refused, retrying...
[2023-07-17 14:15:22.086][I][client_model.py(connect):38] Connection refused, retrying...
[2023-07-17 14:15:29.109][I][client_model.py(connect):38] Connection refused, retrying...
[2023-07-17 14:15:36.127][I][client_model.py(connect):38] Connection refused, retrying...
[2023-07-17 14:15:43.149][I][client_model.py(connect):38] Connection refused, retrying...
[2023-07-17 14:15:50.190][I][client_model.py(connect):38] Connection refused, retrying...
[2023-07-17 14:15:57.223][I][client_model.py(connect):38] Connection refused, retrying...
[2023-07-17 14:16:04.283][I][client_model.py(connect):38] Connection refused, retrying...
[2023-07-17 14:16:11.326][I][client_model.py(connect):38] Connection refused, retrying...
[2023-07-17 14:16:18.350][I][client_model.py(connect):38] Connection refused, retrying...
[2023-07-17 14:16:25.372][I][client_model.py(connect):38] Connection refused, retrying...
[2023-07-17 14:16:32.392][I][client_model.py(connect):38] Connection refused, retrying...
[2023-07-17 14:16:39.435][I][client_model.py(connect):38] Connection refused, retrying...
[2023-07-17 14:16:46.497][I][client_model.py(connect):38] Connection refused, retrying...
[2023-07-17 14:16:53.529][I][client_model.py(connect):38] Connection refused, retrying...
[2023-07-17 14:17:00.546][I][client_model.py(connect):38] Connection refused, retrying...
[2023-07-17 14:17:07.579][I][client_model.py(connect):38] Connection refused, retrying...
[2023-07-17 14:17:14.600][I][client_model.py(connect):38] Connection refused, retrying...
[2023-07-17 14:17:21.632][I][client_model.py(connect):38] Connection refused, retrying...
[2023-07-17 14:17:28.646][I][client_model.py(connect):38] Connection refused, retrying...
[2023-07-17 14:17:33.650][I][client_model.py(connect):31] Connected to the server
[2023-07-17 14:17:35.839][I][client_model.py(send_message):49] VERIFICATIONCODE|adsf@adsf.com 전송
[2023-07-17 14:17:36.259][I][client_model.py(receive_messages):57] Send email fail 수신
[2023-07-17 14:21:49.190][I][client_model.py(send_message):49] VERIFICATIONCODE|longguo0318@naver.com 전송
[2023-07-17 14:21:49.445][I][client_model.py(receive_messages):57] Send email fail 수신
